# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e32514a0d68648c24fcf42cd73c19362e0748ec63233fd53b555b59c3bf21856ba2822fb3caf5164e21ba4cd8bb56fdc46d3932f7a12435e5f2acaa672f9e42

test:
  secret_key_base: 5e0f02590a3e2bda01e8055e2f788b478d17102bf5fd2e2a693c0e46c25f3401d4ca63c5f21f6a31788c488428089cc77983ba4d1d94f0e31237508887584a13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
